unit Model.User.UserCollection;

interface

uses
  MVCFramework.Serializer.Commons,
  MVCFramework.ActiveRecord,
  MVCFramework.Nullables;

type
  [MVCNameCase(ncLowerCase)]
  [MVCTable('User.UserCollection')]
  TUserCollection = class(TMVCActiveRecord)
  private
    [MVCTableField('ID', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;

    [MVCTableField('UserID')]
    FUserID: Int64;

    [MVCTableField('CollectionID')]
    FCollectionID: Int64;

  public
    property ID: Int64 read FID write FID;
    property UserID: Int64 read FUserID write FUserID;
    property CollectionID: Int64 read FCollectionID write FCollectionID;
  end;

implementation

end.

