unit Model.Book.AccessibilityDetail;

interface

uses
  MVCFramework.Serializer.Commons,
  MVCFramework.ActiveRecord,
  MVCFramework.Nullables;

type
  [MVCNameCase(ncLowerCase)]
  [MVCTable('Book.AccessibilityDetail')]
  TAccessibilityDetail = class(TMVCActiveRecord)
  private
    [MVCTableField('ID', [foPrimaryKey, foAutoGenerated])]
    FID: Int64;

    [MVCTableField('AccessibilityGroupID')]
    FAccessibilityGroupID: Int64;

    [MVCTableField('UserID')]
    FUserID: Int64;

    [MVCTableField('Priority')]
    FPriority: NullableInt64;

  public
    property ID: Int64 read FID write FID;
    property AccessibilityGroupID: Int64 read FAccessibilityGroupID write FAccessibilityGroupID;
    property UserID: Int64 read FUserID write FUserID;
    property Priority: NullableInt64 read FPriority write FPriority;
  end;

implementation

end.

