Unit Model.Book.Comment;

Interface
Uses
    MVCFramework.Serializer.Commons,
    MVCFramework.ActiveRecord,
    MVCFramework.Nullables;
Type
    [MVCNameCase(ncLowerCase)]
    [MVCTable('Book.Comment')]
    TComment = class(TMVCActiveRecord)
    Private
        [MVCTableField('CommentID', [foPrimaryKey, foAutoGenerated])]
        FCommentID: Int64;

        [MVCTableField('UserID')]
        FUserID: Int64;

        [MVCTableField('BookID')]
        FBookID: Int64;

        [MVCTableField('Text')]
        FText: NullableString;

        [MVCTableField('CommentRefID')]
        FCommentRefID: NullableInt64;

        [MVCTableField('CreatedAt')]
        FCreatedAt: TDateTime;

        [MVCTableField('LikeCount')]
        FLikeCount: NullableInt32;

        [MVCTableField('DisLikeCount')]
        FDisLikeCount: NullableInt32;

        [MVCTableField('IsBlocked')]
        FIsBlocked: NullableBoolean;

        [MVCTableField('IsEdited')]
        FIsEdited: NullableBoolean;

        [MVCTableField('IsSpoiled')]
        FIsSpoiled: NullableBoolean;

        [MVCTableField('ReportCount')]
        FReportCount: NullableInt32;

        [MVCTableField('ReportID')]
        FReportID: NullableInt64;

    Public
        Property CommentID: Int64 read FCommentID write FCommentID;
        Property UserID: Int64 read FUserID write FUserID;
        Property BookID: Int64 read FBookID write FBookID;
        Property Text: NullableString read FText write FText;
        Property CommentRefID: NullableInt64 read FCommentRefID write FCommentRefID;
        Property CreatedAt: TDateTime read FCreatedAt write FCreatedAt;
        Property LikeCount: NullableInt32 read FLikeCount write FLikeCount;
        Property DisLikeCount: NullableInt32 read FDisLikeCount write FDisLikeCount;
        Property IsBlocked: NullableBoolean read FIsBlocked write FIsBlocked;
        Property IsEdited: NullableBoolean read FIsEdited write FIsEdited;
        Property IsSpoiled: NullableBoolean read FIsSpoiled write FIsSpoiled;
        Property ReportCount: NullableInt32 read FReportCount write FReportCount;
        Property ReportID: NullableInt64 read FReportID write FReportID;
End;

Implementation

End.

